name: Synopsys Action
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
## Please change the project name to your Blackdcuk project here for scan using INTELLIGENT mode 
env:
     DETECT_PROJECT_NAME: vue-shopping
     DETECT_PROJECT_VERSION_NAME: actions 
jobs:
  synopsys-action:
  runs-on: [ ubuntu-latest ]
    steps:
     - uses: actions/checkout@v2
     - name: Set up Java 11
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
     - name: Setup Maven Action
       uses: s4u/setup-maven-action@v1.5.1
       with:
         java-version: 11   
     - name: Black Duck Scan
       uses: synopsys-sig/synopsys-action@v1.8.0

       with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_fixpr_enabled: true
          blackduck_prComment_enabled: true
          blackduck_automation_fixpr: true
          blackduck_automation_prcomment: true
          
